version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq_data
    networks:
      - tpm-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .

    ports:
      - "5000:5000"
      - "5672:5672" # RabbitMQ
    
    networks:
      - tpm-net
volumes:
  rabbitmq_data:

secrets:
  hmac_secret:
    file: ./hmac_secret.key

networks:
  tpm-net:
    name: tpm-net
    driver: bridge