name: TPM Handler Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged --security-opt seccomp=unconfined
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      swtpm:
        image: ghcr.io/stefanberger/swtpm:v0.8.0
        ports:
          - 2321:2321

    steps:
    - uses: actions/checkout@v4
    # ... rest of your steps remain the same ...
