name: TPM Handler Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --privileged --security-opt seccomp=unconfined
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      swtpm:
        image: ibmswtpm/swtpm
        ports:
          - 2321:2321

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        dnf update -y
        dnf install -y \
          python3.11 \
          python3-pip \
          libtss2-devel \
          tpm2-tss \
          tpm2-tools \
          gcc \
          openssl-devel

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install project dependencies
      run: |
        pipenv install --dev
        pipenv run python -m pip install --upgrade pip

    - name: Configure TPM emulator
      run: |
        mkdir -p /tmp/tpm
        swtpm socket \
          --tpmstate dir=/tmp/tpm \
          --ctrl type=tcp,port=2321 \
          --tpm2 \
          --daemon

    - name: Run tests
      run: pipenv run pytest -v --cov=src --cov-report=xml
      env:
        RABBITMQ_HOST: rabbitmq
        TPM_SERVER: swtpm

    - name: Security scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/ci
